name: Build

on:
  push:
    paths:
      - .github/workflows/main.yml
      - biome.json
      - tsconfig.json
      - package.json
      - bun.lockb
      - '**.ts'

jobs:
  build:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
